### PR TITLE
add TLS summary doc

### PR DESCRIPTION
**Pull request by hokiespurs**
- added summary doc explaining Total Least Squares
- pdf has not been thoroughly editted, but it's better documentation than nothing!

### CODE REVIEW

**Comment by hokiespurs** [comment]
I realized I didn't push any documentation on TLS... attached is a pdf explaining the nomenclature, and a very simple example of running the lsrtls script.

**Comment by hokiespurs** [comment]
Shoot, i'm trying to merge into master like a dummy... but looks like @allisonpenko, @mpalmsten, and @KateBrodie haven't locked down the repo so I can merge without a review!
😃

**Comment by RobHolman** [comment]
Attached??

Rob Holman
SECNAV/CNO Chair in Oceanography

104 Ocean Admin Bldg.
CEOAS-OSU
Corvallis, Oregon, USA 97331-5503
ph: 1-541-737-2914
holman@coas.oregonstate.edu
http://cil-www.coas.oregonstate.edu

**Comment by hokiespurs** [comment]
@RobHolman, sorry, I used bad nomenclature. Not "attached", but "included in this pull request"

**Pull request merged**
